# Configurações do banco de dados PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost/afrodite
    username: @db.user@
    password: @db.password@
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate

# Configuracao do servidor da aplicacao
server:
  port: 8080
  servlet:
    context-path: /api
