version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=afrodite'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'